### PR TITLE
Add TypeScript type definitions

### LINKED ISSUE #1: TypeScript types
Would be nice if this library would provide TS types as well. I'm using the following WIP types in my app locally right now:

```ts
// TODO remove this once `@sqlite.org/sqlite-wasm` has types
declare module '@sqlite.org/sqlite-wasm' {
  export type TODO = any

  interface Window {
    // eslint-disable-next-line @typescript-eslint/consistent-type-imports
    sqlite3InitModule: (_?: TODO) => Promise<import('./sqlite3').Sqlite3>
  }

  export type Sqlite3 = {
    oo1: {
      DB: new (options?: OO1DBOptions) => DB
      OpfsDb: new (filename: string, mode: string) => DB
    }
    opfs?: {
      debug: TODO
      deleteEntry: TODO
      entryExists: TODO
      metrics: TODO
      mkdir: TODO
      randomFilename: TODO
      registerVfs: TODO
      rootDirectory: TODO
    }
    capi: {
      sqlite3_deserialize: TODO
      [key: string]: TODO
    }
    wasm: {
      allocFromTypedArray: (typedArray: Uint8Array) => number
      [key: string]: TODO
    }
  }

  /** https://sqlite.org/wasm/doc/trunk/api-oo1.md#db-ctor */
  export type OO1DBOptions = {
    /** @default ':memory:' */
    filename?: string
    /** open-mode flags */
    flags?: string
    /** name of the sqlite3_vfs to use */
    vfs?: string
  }

  export declare const InitWasm: () => Promise<Sqlite3>

  export default InitWasm

  export class DB {
    filename: string
    pointer: TODO

    affirmOpen(): DB

    changes(total: boolean, sixtyFour: boolean): number

    exec(options: ExecOptions): TODO
    exec(query: FlexibleString, options?: ExecOptions): TODO
    close(): DB
    export(): TODO
    /**
     * @example aDb.prepare("INSERT INTO foo(a) VALUES(?)").bind(123).stepFinalize();
     */
    prepare(query: FlexibleString): Stmt

    checkRc(db: TODO, resultCode: TODO)

    createFunction(): TODO

    dbFilename(): string

    dbName(): string
  }

  export type ExecOptions = {
    sql?: FlexibleString
    bind?: Bindable
    // saveSql?: TODO

    returnValue?: 'this' | 'resultRows' | 'saveSql'

    rowMode?: 'array' | 'object' | 'stmt'

    resultRows?: TODO[]
  }

  export type FlexibleString = string | Uint8Array | Int8Array | string[]

  /** https://sqlite.org/wasm/doc/trunk/api-oo1.md#stmt-properties */
  export interface Stmt {
    columnCount: number
    parameterCount: number
    pointer: TODO

    bind(bindable: Bindable): Stmt
    bind(indexOrParameterName: number | string, bindable: Bindable): Stmt

    stepFinalize(): boolean
  }

  export type Bindable = BindableValue[] | Record<string, BindableValue>

  export type BindableValue = null | undefined | number | boolean | string | Uint8Array | Int8Array
}

```

### PR DESCRIPTION
**Pull request by jbaiter**
Adds TypeScript type definitions for all publicly exposed APIs of the official 3.43.0 build of SQLite's WASM build. Based on initial work by @schickling, @mizchi and @tomayac in #36. Fixes #1.

In addition to the type definitions, every function, struct and class has a docstring. For most APIs this mirrors the online documentation, for the `sqlite.capi` namespace the docstrings are abbreviated versions of the docstrings in `sqlite.h`, with a hyperlink to the full documentation. Docstrings for `sqlite.capi` functions also include the original C signature, which can be essential when dealing with pointer types.

### CODE REVIEW

**Comment by sampbarrow** [comment]
@jbaiter This is great, thanks! Been doing some testing - looks like there's one discrepancy.

```sqlite3_create_function(
db: number | Database,
functionName: string | number,
nArg: number,
eTextRep: 1,
pApp: number,
xFunc: number | ((ctx: number, nArg: number, args: number) => SqlValue),
xStep: number | ((ctx: number, nArg: number, args: number) => void),
xFinal: number | ((ctx: number) => SqlValue)) => number
)```

But the sqlite wasm [docs](https://sqlite.org/wasm/doc/trunk/api-c-style.md#sqlite3_create_function) mention some changes which also came up in my testing.

> The semantics of generated JS wrappers are:
> 
> xFunc(): passed (pCtx, ...values). Its return value becomes the new SQL function's result.
> xStep() and xInverse() (window functions): passed (pCtx, ...values). The return value is ignored.
> xFinal(): is passed (pCtx). Its return value becomes the new aggregate SQL function's result.

So I guess this would be:

```sqlite3_create_function(
db: number | Database,
functionName: string | number,
nArg: number,
eTextRep: 1,
pApp: number,
xFunc: number | ((ctx: number, **...values: SqlValue[]**) => SqlValue),
xStep: number | ((ctx: number, **...values: SqlValue[]**) => void),
xFinal: number | ((ctx: number) => SqlValue)) => number
)```

This would line up with what I'm seeing at runtime as well.

**Comment by jbaiter** [comment]
Thank you for testing the types! I've pushed a fix.

**Comment by tomayac** [comment]
Let me know when it's ready to be merged.

**Comment by sampbarrow** [comment]
Thanks @jbaiter. Couple more things I found.

1. SqlValue should include bigint, if I understand correctly? They work fine at runtime.
2. Can `readonly SqlValue[]` be added as a possible BindingSpec type? This doesn't need to be a mutable array does it? 

```
    /** Types of values that can be passed to/retrieved from SQLite. */
    type SqlValue =
        | string
        | number
        | null
        | Uint8Array
        | Int8Array
        | ArrayBuffer
        | bigint

    /** Specifies parameter bindings. */
    type BindingSpec =
        | SqlValue[]
        | readonly SqlValue[]
        | { [paramName: string]: SqlValue }
        /** Assumed to have binding index `1` */
        | SqlValue;
```

**Comment by jbaiter** [comment]
@sampbarrow 
>     1. SqlValue should include bigint, if I understand correctly? They work fine at runtime.

Indeed it should! Fixed, thank you!

>     2. Can `readonly SqlValue[]` be added as a possible BindingSpec type? This doesn't need to be a mutable array does it?

Oh absolutely, thank you for pointing that out, added the modifier in some other function signatures as well 👍🏾

@tomayac 
> Let me know when it's ready to be merged.

That probably depends on your definition of 'ready' as a maintainer 😅 . The API surface is huge, and I've done the types to the best of my knowledge, but there's bound to be gaps and mistakes in there that I overlooked. Maybe @sgbeal could take a glance at the types and see if anything obviously wrong jumps out at him?

**Comment by chuanqisun** [comment]
Is it possible to release the typescript support with the npm "pre-release" semantic version bump, so the community can try it out in their realistic projects and provide feedback?

**Comment by chuanqisun** [comment]
The `build1` part seems unconventional for npm versioning. I'm not sure how semver prerelease would be handled if we append more text after it. My hunch is that the `build1` is already being treated as a prerelease tag so the users will not get automatic patch version bumps when they use `^3.43.1`, but someone please confirm this.

Since the `alpha` does not have any special meaning to npm, it could potentially just be the `build` instead. So something like `npm version prerelease --preid=build` would give us `v3.43.1-build.0` -> `v3.43.1-build.1` -> `v3.43.1-build.2`.

**Review by tomayac — APPROVED** [review]
LGTM and pre-releasing to test this in practice, as agreed on in the PR thread.

**Pull request merged**
