### PR TITLE
Add types for `Sqlite3Worker1Promiser`

### PR DESCRIPTION
**Pull request by sameoldlab**

### CODE REVIEW

**Comment by sameoldlab** [comment]
Progress: 
- Mostly done with `Sqlite3Worker1PromiserConfig`. Not sure what goes in for the args of `generateMessageId`
- Need clearer documentation for `Promiser` Method `open`'s `filename` and `vfs`
-  `exec` needs to add a full list of arguments, js eqivalent for sql `VALUE` value used in row and bind
- Need to add type for `Promiser` response error stack trace array
- There is additional metadata returned by `Promiser`. Described as "// possibly other metadata ..." on sqlite docs. Not sure how stable these are / if they should be documented here.

As the methods are very similar to worker1, I'm hoping I can reduce what is specified here and reuse the existing types where possible.

**Comment by sameoldlab** [comment]
> How does this relate to #54? Could you maybe join forces?
Yes, It's for the same issue. I made my PR against the [sqlite:types-improvement](https://github.com/sqlite/sqlite-wasm/tree/types-improvement) branch, so ideally that could get merged to main when everything is complete.

**Comment by sameoldlab** [comment]
In that case would it make more sense for me to mark this as ready for review now and then track progress in https://github.com/sqlite/sqlite-wasm/pull/54?

**Comment by tomayac** [comment]
I think so, yes. Please ask someone from #54 for a review, and let's then merge it, so from thereon you can continue working on #54. Thanks!

**Pull request merged**
