### PR TITLE
Remove `SqliteClient`

### PR DESCRIPTION
**Pull request by tomayac**
As discussed in https://github.com/sqlite/sqlite-wasm/pull/43, this PR removes `SqliteClient`.

CC: @etiennenoel

### CODE REVIEW

**Comment by DallasHoff** [comment]
Perhaps we could add a list of links in the README pointing to client libraries based on sqlite-wasm? Giving users some direction in lieu of this removal.

**Comment by tomayac** [comment]
> Perhaps we could add a list of links in the README pointing to client libraries based on sqlite-wasm? Giving users some direction in lieu of this removal.

Linking to a curated list risks getting outdated and by definition isn't neutral. An idea could be to link to [npm dependents](https://www.npmjs.com/browse/depended/@sqlite.org/sqlite-wasm).

**Comment by DallasHoff** [comment]
Yeah, that's a good idea. NPM provides an authoritative, auto-updating list ready to go.

**Review by etiennenoel — APPROVED** [review]

**Comment by tomayac** [comment]
I will release this after the weekend.

**Pull request merged**
